# First task, create base workflow (without any job)
name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
# Second task to be created, a new base job 
jobs:
  welcome:
    name: Post welcome comment
    runs-on: ubuntu-latest
# Third task to be created, adding a new step
    steps:
      # GithubCLI command to add a new comment in a PR created
      - run: gh pr comment "$PR_URL" --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
